<div id="sign-up">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="text-center">
                    <h1>Don't have an account?</h1>
                    <!--<p class="lead">Your best teamwork awaits, start your <strong>free</strong> 14-day trial!</p>-->
                    <h2><small>It's easy and <strong>free</strong> to get started. Just fill in the details below and click the get started button.</small></h2>
                    <div class="vertical-tab-sm"></div>
                </div>
                <div class="panel panel-default bg-default">
                    <div class="panel-body">
                        <form class="form-inline" role="form">
                            <div class="form-group  col-md-4">
                                <label class="sr-only" for="church-name">Your church name</label>
                                <input type="text" class="form-control input-lg input-block" id="church-name" placeholder="Your church name">
                            </div>
                            <div class="form-group col-md-3">
                                <label class="sr-only" for="email">Your email address</label>
                                <input type="email" class="form-control  input-lg input-block" id="email" placeholder="Your email address">
                            </div>
                            <div class="form-group col-md-2">
                                <label class="sr-only" for="password">Password</label>
                                <input type="password" class="form-control  input-lg input-block" id="password" placeholder="Password">
                            </div>
                            <label class="sr-only" for="proceed">Proceed</label>
                            <button type="submit" id="proceed" class="btn btn-success col-lg-3 input-lg ">Get Started</button>
                        </form>
                    </div>
                </div>
                <div>
                    <div class='col-xs-12 vertical-tab-sm'></div>
                    <p class='text-center'>Already have an account? <a>Log in here</a></p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class='col-xs-12 vertical-tab-md hidden-xs hidden-sm'></div>
            <div class='col-xs-12 vertical-tab-sm visible-xs visible-sm'></div>
        </div>
    </div>
</div>