<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class='col-md-4 col-md-offset-4'>
                    <div class="vertical-tab-md"></div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h2 class='text-center'><?php echo $this->translate('Password Changed'); ?></h2>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="vertical-tab-sm"></div>
                            <p><?php
                                $this->layout('layout/site');
                                echo $this->translate('Your password has been changed. You can now login using your new password.')
                                ?></p>
                            <p> <a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Back to login.'); ?></a></p>
                        </div>
                        <div class="vertical-tab-sm"></div>
                    </div>
                    <div class="vertical-tab-md"></div>
                    <div class="vertical-tab-md"></div>
                </div>
            </div>
        </div>
    </div>
</div>