<?php // modal hidden, by default due to .modal class   ?>
<div id="modal" tabindex="-1" role="dialog" aria-labelledby="modal-title" aria-hidden="true" class="modal">
    <div class="modal-dialog [modal-lg|modal-sm]">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 id="modal-title" class="modal-title">Lorem Ipsum - Dummy Text Lorem Ipsum - Dummy Text Lorem Ipsum - Dummy Text </h4>
            </div>
            <div class="modal-body">
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting
                    industry. Lorem Ipsum has been the industry's standard dummy
                    text ever since the 1500s, when an unknown printer took
                    a galley of type and scrambled it to make a type specimen book.
                    It has survived not only five centuries, but also the leap
                    into electronic typesetting, remaining essentially unchanged.
                    It was popularised in the 1960s with the release of Letraset
                    sheets containing Lorem Ipsum passages, and more recently with
                    desktop publishing software like Aldus PageMaker including versions
                    of Lorem Ipsum.</p>

                <p>It is a long established fact that a reader will
                    be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem
                    Ipsum is that it has a more-or-less normal distribution of
                    letters, as opposed to using 'Content here, content here',
                    making it look like readable English. Many desktop publishing
                    packages and web page editors now use Lorem Ipsum as their default
                    model text, and a search for 'lorem ipsum' will uncover many
                    web sites still in their infancy. Various versions have evolved
                    over the years, sometimes by accident, sometimes on purpose
                    (injected humour and the like).</p></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <!--dynamically append inline class 'btn' type elements eg <a href="#" class="btn btn-primary">Save Changes</a>-->
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->