<?php $this->headTitle('Change Password'); ?>
<?php $this->layout('layout/change_password'); ?>
<div class='col-sm-12'>
    <?php
    $form = $this->changePasswordForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/changepassword'));
    $form->setAttribute('method', 'post');
    $emailElement = $form->get('identity');
    $emailElement->setValue($this->zfcUserIdentity()->getEmail());
    $form->setAttribute('class', 'form-horizontal');
    ?>
    <!--open form-->
    <?= $this->form()->openTag($form); ?>
    <!--end open form-->
    <!--no need for edit as will always be viewed in edit mode-->
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-6">
                    <h3><?=
                        sprintf($this->translate('Change Password for %s'),
                                $this->zfcUserDisplayName());
                        ?></h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <?php if ($status === true) : ?>
                    <div class="alert bg-success text-white"><?php echo $this->translate('Password changed successfully.'); ?></div>
                    <?php elseif ($status === false) : ?>
                        <div class="alert bg-warning text-white"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 vertical-tab-sm"></div>
                <div class="co-sm-6">
                    <?php echo $this->formElementErrors($form->get('identity')); ?>
                    <?php echo $this->formInput($form->get('identity')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <?php echo $this->formLabel($form->get('credential')); ?>
                    <?php
                    $credential = $form->get('credential');
                    $credential->setAttribute('class', 'form-control');
                    echo $this->formInput($credential);
                    ?>
                    <div class="validation-messages">
                        <p class="text-danger"> <?= $this->formElementErrors($form->get('credential')) ?></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <?php echo $this->formLabel($form->get('newCredential')); ?>
                    <?php
                    $newCredential = $form->get('newCredential');
                    $newCredential->setAttribute('class', 'form-control');
                    echo $this->formInput($newCredential);
                    ?>
                    <div class="validation-messages">
                        <p class="text-danger"> <?= $this->formElementErrors($form->get('newCredential')) ?></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <?php echo $this->formLabel($form->get('newCredentialVerify')); ?>
                    <?php
                    $newCredentialVerify = $form->get('newCredentialVerify');
                    $newCredentialVerify->setAttribute('class', 'form-control');
                    echo $this->formInput($newCredentialVerify);
                    ?>
                    <div class="validation-messages">
                        <p class="text-danger"> <?= $this->formElementErrors($form->get('newCredentialVerify')) ?></p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="vertical-tab-xs"></div>
                    <?php
                    $submit = $form->get('submit');
                    $submit->setValue('Save Details');
                    $submit->setAttribute('class',
                            'btn btn-block btn-success btn-lg');
                    echo $this->formInput($submit);
                    ?>
                </div>
            </div>

        </div>
    </div>
    <!--close form-->
    <?= $this->form()->closeTag(); ?>
    <!--end close form-->
</div>
