<?php $this->headTitle('Change Email'); ?>
<?php $this->layout('layout/change_email'); ?>
<div class='col-sm-12'>
    <?php
    $form = $this->changeEmailForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/changeemail'));
    $form->setAttribute('method', 'post');
    $form->setAttribute('class', 'form-horizontal');
    ?>
    <!--open form-->
    <?= $this->form()->openTag($form); ?>
    <!--end open form-->
    <!--no need for edit as will always be viewed in edit mode-->
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-6">
                    <h3><?php
                        echo sprintf($this->translate('Change Email for %s'),
                                $this->zfcUserDisplayName());
                        ?></h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <?php if ($status === true) : ?>
                    <div class="alert bg-success text-white"><?php echo $this->translate('Email address changed successfully.'); ?></div>
                    <?php elseif ($status === false) : ?>
                        <div class="alert bg-warning text-white"><?php echo $this->translate('Unable to update your email address. Please try again.'); ?></div>
                    <?php endif; ?>
                </div>
            </div>
            <?php foreach ($form as $element): ?>
            <div class="row">
                    <div class="col-sm-6">
                        <?php if ($element->getLabel() != null): ?>
                            <?php echo $this->formLabel($element); ?>
                        <?php endif ?>
                        <?php if ($element instanceof Zend\Form\Element\Button): ?>
                            <?php
                            $element->setAttribute('class', 'form-control');
                            echo $this->formButton($element);
                            ?>
                        <div class="validation-messages">
                                    <p class="text-danger"> </p>
                                </div>
                            <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>

                                <?php echo $this->formCaptcha($element); ?>
                                <?php echo $this->formElementErrors($element); ?>
                                <div class="validation-messages">
                                    <p class="text-danger"> </p>
                                </div>
                            <?php else: ?>
                                <?php
                                $element->setAttribute('class', 'form-control');
                                echo $this->formInput($element);
                                ?>
                                <?php echo $this->formElementErrors($element); ?>
                                <div class="validation-messages">
                                    <p class="text-danger"> </p>
                                </div>
                            <?php endif ?>
                        </div>
                    </div>
                <?php endforeach; ?>
                <div class="row">
                    <div class="col-sm-6">
                    <div class="vertical-tab-xs"></div>
                    <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
                    <?php endif; ?>
                    <input type="submit" class="btn btn-block btn-success btn-lg" value="Save Details" />
                </div>
            </div>
        </div>
    </div>
    <!--close form-->
    <?= $this->form()->closeTag(); ?>
    <!--end close form-->
</div>
