<?php $this->headTitle('Sign In'); ?>
<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class='form-login-wrapper'>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h2 class='text-center'><?php echo $this->translate('Welcome Back'); ?></h2>
                            </div>
                        </div>
                        <div class="panel-body">
                            <?php
                            $form = $this->loginForm;
                            $form->prepare();
                            $form->setAttribute('action',
                                    $this->url('zfcuser/login'));
                            $form->setAttribute('method', 'post');
                            ?>
                            <?php echo $this->form()->openTag($form) ?>

                            <?php echo $this->formElementErrors($form->get('identity')) ?>
                            <div class='form-group'>
                                <?php echo $this->formLabel($form->get('identity')) ?>
                                <?php
                                echo $this->formInput($form->get('identity')->setAttribute('class',
                                                'form-control'));
                                ?>
                            </div>
                            <div class='form-group'>
                                <?php echo $this->formLabel($form->get('credential')) ?>
                                <?php
                                echo $this->formInput($form->get('credential')->setAttribute('class',
                                                'form-control'));
                                ?>
                            </div>
                            <div class="form-group">
                                <?php
                                if ($form->has('captcha')) {
                                   $captcha = $form->get('captcha');
                                    echo $this->formLabel($captcha);
                                    echo $this->formCaptcha($captcha);
                                    echo $this->formElementErrors($captcha);
                                }
                                ?>
                            </div>
                            <div class="form-group">
                                <?php if ($this->redirect): ?>
                                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                                <?php endif ?>
                                <?php
                                $submit = $form->get('submit');
                                $submit->setAttribute('class',
                                        'btn btn-block btn-xl btn-success');
                                ?>
                                    <?php echo $this->formButton($submit) ?>
                            </div>
                            <div class="form-group">
                                <div class="vertical-tab-xs"></div>
                                <!--<div class="col-md-5"><p class="text-center"><a class="hidden" href="">Join your church</a></p></div>-->
                                <div class="col-md-12"><p class="text-center">Can't login? <a  href="<?php echo $this->url('zfcuser/forgotpassword') ?>">Reset password</a></p></div>
                                <?php if ($this->enableRegistration) : ?>
                                    <?php //echo $this->translate('Not registered?');      ?>
                                                                                                                        <!--<a href="<?php //echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect=' . $this->redirect : '')                        ?>"><?php // echo $this->translate('Sign up!');                        ?></a>-->
                                <?php endif; ?>
                            </div>
                            <?php echo $this->form()->closeTag() ?>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>