<p>We've received a request to reset your password.</p>

<p><a href="<?=
      $this->serverUrl($this->url('reset_password',
                      array('hashed_user_id' => $this->hashId($this->userId),
                  'token' => $this->requestKey)))
      ?>">Click here to change your password.</a></p>

<p><b>Don't recognize this activity?</b></p>
<p>If you didn't request a new password, let us know immediately.</p>