<p>We've received a request to reset your password. To reset your password, click
    the link below.</p>
<?php
$resetPasswordLink = $this->serverUrl($this->url('reset_password',
                array('hashed_user_id' => $this->hashId($this->userId),
            'token' => $this->requestKey)))
?>
<p><?= $resetPasswordLink ?></p>

<p> If the above link is not clickable, please copy the whole link and
    paste it in your browser.</p>

<p><b>Don't recognize this activity?</b></p>
<p>If you didn't request a new password, let us know immediately.</p>
<!--use timestamp to avoid collapsing by gmail-->
<p>#<?= time(); ?></p>