<div class="container">
    <?php $this->layout('layout/password_sent');
    ?><h1><?php echo $this->translate("Check your email."); ?></h1>
    <?php
    if ($this->error) {
        ?>
            <p>An error occurred.</p>
        <?php
    } else {
        ?>
        <p><?php
        echo sprintf($this->translate('A reminder has been sent to your e-mail address %s.'),
                $this->escapeHtml($this->email));
        ?>  You may need to check your spam folder.</p>
    <?php
    }
    ?>
    

    <a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Back to login?'); ?></a>
</div>