<div class="">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class='col-md-4 col-md-offset-4'>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="panel-title">
                                <h2 class='text-center'><?php echo $this->translate('Change Password'); ?></h2>
                            </div>
                        </div>
                        <div class="panel-body">
                            <p><strong><?php
                                    echo sprintf($this->translate('Email %s'),
                                            $this->escapeHtml($this->email));
                                    ?></strong></p>
                            <?php
                            $this->layout('layout/reset_password');
                            $form = $this->resetForm;

                            $form->prepare();
                            $form->setAttribute('action',
                                    $this->url('reset_password',
                array('userId' => $this->userId, 'token' => $this->token)));
                            $form->setAttribute('method', 'post');

                            echo $this->form()->openTag($form);
                            ?>
                            <div class='form-group'>
                                <?php echo $this->formLabel($form->get('newCredential')); ?>
                                <?php
                                $elementNewCredential = $form->get('newCredential');
                                $elementNewCredential->setAttribute('class',
                                        'form-control');
                                echo $this->formInput($elementNewCredential) . $this->formElementErrors($elementNewCredential);
                                ?>
                            </div>
                            <div class="form-group">
                                <?php
                                echo $this->formLabel($form->get('newCredentialVerify'));
                                $elementNewCredentialVerify = $form->get('newCredentialVerify');
                                $elementNewCredentialVerify->setAttribute('class',
                                        'form-control');
                                echo $this->formInput($elementNewCredentialVerify) . $this->formElementErrors($elementNewCredentialVerify);
                                ?>
                            </div>
                            <div class="form-group">
                                <?php
                                $submit = $form->get('submit');
                                $submit->setAttribute('class',
                                        'btn btn-lg btn-success btn-block');
                                echo $this->formButton($submit);
                                ?>
                            </div>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>